// This file will contain all the mock data for the PCC prototype.
// It will serve as our single source of truth for products, SKUs, etc. 

import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '5124922',
    name: 'Premium Company Page',
    description: 'Get exclusive access to insights, invite your page followers and customized your page to market to the right people to grow your business.',
    lob: 'Premium',
    category: 'Premium Company Page',
    status: 'Active',
    productType: 'Subscription',
    skus: [
      {
        id: 'sku_5124922a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Annual',
        billingFrequency: '12 Months',
        digitalGoods: ['Customized Page', 'Follower Insights'],
        taxClass: 'SUBDIG',
        prices: [{ status: 'Active', pricePoints: [{ currencyCode: 'USD', amount: 1199.4 }] }],
      },
    ],
  },
  {
    id: '5095285',
    name: 'Premium Career',
    description: 'Get exclusive access to insights, job search tools, and direct messaging to reach the right people to grow your career.',
    lob: 'Premium',
    category: 'Premium Generic Products',
    status: 'Active',
    productType: 'Subscription',
    skus: [
      {
        id: 'sku_5095285a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        billingFrequency: '1 Month',
        digitalGoods: ['Applicant Insights', '5 InMail Messages/month'],
        taxClass: 'SUBDIG',
        prices: [{ status: 'Active', pricePoints: [{ currencyCode: 'USD', amount: 29.99 }] }],
      },
      {
        id: 'sku_5095285b',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Annual',
        billingFrequency: '12 Months',
        digitalGoods: ['Applicant Insights', '5 InMail Messages/month'],
        taxClass: 'SUBDIG',
        prices: [{ status: 'Active', pricePoints: [{ currencyCode: 'USD', amount: 239.88 }] }],
      },
    ],
  },
  {
    id: '5095295',
    name: 'Premium Business',
    description: 'Get exclusive access to insights, search tools, and direct messaging to reach the right people to grow your business.',
    lob: 'Premium',
    category: 'Premium Generic Products',
    status: 'Active',
    productType: 'Subscription',
    skus: [
      {
        id: 'sku_5095295a',
        status: 'Active',
        region: 'EMEA',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        billingFrequency: '1 Month',
        digitalGoods: ['Business Insights', '15 InMail Messages/month'],
        taxClass: 'SUBDIG',
        prices: [{ status: 'Active', pricePoints: [{ currencyCode: 'EUR', amount: 49.99 }] }],
      },
    ],
  },
  {
    id: '5241848',
    name: 'Premium Career Duo',
    description: 'Get exclusive access to insights, job search tools, and direct messaging to reach the right people to grow your career.',
    lob: 'Premium',
    category: 'Premium Multiseat',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5241858',
    name: 'Premium Business Duo',
    description: 'Get exclusive access to insights, search tools, and direct messaging to reach the right people to grow your business.',
    lob: 'Premium',
    category: 'Premium Multiseat',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5255644',
    name: 'Premium Business Suite',
    description: 'Get exclusive access to insights, search tools, and direct messaging to reach the right people to grow your business.',
    lob: 'Premium',
    category: 'Premium Small Business',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5083684',
    name: 'Recruiter Lite Teams',
    description: 'Find the right talent faster. Search for qualified candidates with 20+ filters, 30 InMail messages per month, saved search alerts, daily candidate recommendations, among other features.',
    lob: 'LTS',
    category: 'RLite',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5073467',
    name: 'Sales Navigator Advanced',
    description: 'Forge deeper relationships by leveraging real-time sales intelligence and seamless collaboration with your team. Receive relevant, accurate insights on buyer interest and enhance the experience of other sales tools by embedding LinkedIn insights. Includes 50 InMail messages per month, Buyer Interest, BI Integrations, List Sharing, Smart Links, TeamLink, and other features.',
    lob: 'LSS',
    category: 'Placeholder',
    status: 'Active',
    productType: 'Subscription',
    skus: [
      {
        id: 'sku_5073467a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Field',
        billingCycle: 'Annual',
        billingFrequency: '12 Months',
        digitalGoods: ['TeamLink', '50 InMail Messages/month', 'Buyer Interest'],
        taxClass: 'SUBDIGBNDL',
        prices: [{ status: 'Active', pricePoints: [{ currencyCode: 'USD', amount: 1600.0 }] }],
      },
    ],
  },
  {
    id: '5073477',
    name: 'Sales Navigator TeamLink Extend Seat',
    description: "1000 TeamLink Extend seats which are included with Customer's Sales Navigator Advanced or Advanced Plus purchase.",
    lob: 'LSS',
    category: 'Placeholder',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5106528',
    name: 'Sales Navigator Core Multiseat',
    description: 'Build trusted relationships by using the power of LinkedIn data to find, research, and communicate with customers/prospects. Identify targets quickly and connect with them faster. Includes 50 InMail messages per month, advanced search filters, real-time alerts and other foundational features.',
    lob: 'LSS',
    category: 'Placeholder',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5095305',
    name: 'Sales Navigator Core',
    description: 'Build trusted relationships by using the power of LinkedIn data to find, research, and communicate with customers/prospects. Identify targets quickly and connect with them faster. Includes 50 InMail messages per month, advanced search filters, real-time alerts and other foundational features.',
    lob: 'LSS',
    category: 'Placeholder',
    status: 'Active',
    productType: 'Subscription',
    skus: [
      {
        id: 'sku_5095305a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Annual',
        billingFrequency: '12 Months',
        digitalGoods: ['Core Sales Nav Features', '50 InMail Messages/month'],
        taxClass: 'SUBDIGBNDL',
        prices: [{ status: 'Active', pricePoints: [{ currencyCode: 'USD', amount: 959.88 }] }],
      },
      {
        id: 'sku_5095305b',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        billingFrequency: '1 Month',
        digitalGoods: ['Core Sales Nav Features', '50 InMail Messages/month'],
        taxClass: 'SUBDIGBNDL',
        prices: [{ status: 'Active', pricePoints: [{ currencyCode: 'USD', amount: 99.99 }] }],
      },
    ],
  },
  {
    id: '5243645',
    name: 'Premium Executive',
    description: 'Get exclusive access to insights, search tools, and direct messaging to reach the right people to grow your business.',
    lob: 'Premium',
    category: 'Premium Generic Products',
    status: 'Legacy',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5311202',
    name: 'LIHA Base Tier for RCORP',
    description: 'LinkedIn Hiring Assistant (LIHA) Base SKU for RCORP',
    lob: 'LTS',
    category: 'LIHA Corp',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5311212',
    name: 'LIHA Middle Tier for RCORP',
    description: 'LinkedIn Hiring Assistant (LIHA) Middle SKU for RCORP',
    lob: 'LTS',
    category: 'LIHA Corp',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5311232',
    name: 'LIHA Base Tier for RPS',
    description: 'LinkedIn Hiring Assistant (LIHA) Base SKU for RPS',
    lob: 'LTS',
    category: 'LIHA RPS',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5311242',
    name: 'LiHA Middle Tier for RPS',
    description: 'LinkedIn Hiring Assistant (LIHA) Middle SKU for RPS',
    lob: 'LTS',
    category: 'LIHA RPS',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5071249',
    name: 'LinkedIn Learning for Teams',
    description: 'LinkedIn Learning for teams provides teams with access to high-quality learning content, an intuitive and personalized learning experience, and administrative capabilities to manage learners, recommend content, and measure learning engagement.',
    lob: 'LTS',
    category: 'Learning for Teams',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
  {
    id: '5037084',
    name: 'Recruiter Lite',
    description: 'Recruiter Lite (Only sold through Small Business Solution Packages)',
    lob: 'LTS',
    category: 'RLite',
    status: 'Active',
    productType: 'Subscription',
    skus: [],
  },
]; 