// This file will contain all the mock data for the PCC prototype.
// It will serve as our single source of truth for products, SKUs, etc. 

import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '5124922',
    name: 'Premium Company Page',
    description: 'Get exclusive access to insights, invite your page followers and customized your page to market to the right people to grow your business.',
    lob: 'Premium',
    category: 'Premium Company Page',
    status: 'Active',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://www.linkedin.com/company/premium/',
    seatType: 'Multi-seat fixed',
    isBundle: false,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 7,
    paymentFailurePaidToPaidGracePeriod: 14,
    seatMin: 1,
    seatMax: 10,
    digitalGoods: ['Customized Page', 'Follower Insights', 'Advanced Analytics'],
    tags: [{ type: 'Customer Type', value: 'Enterprise customer' }, { type: 'Sales Top of Funnel', value: 'Web CTA' }],
    isCancellable: true,
    isEligibleForAmendment: true,
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/lsa',
    howToCancelUrl: 'https://www.linkedin.com/help/linkedin/answer/a134000',
    productUrl: 'https://www.linkedin.com/premium/company-page',
    skus: [
      {
        id: 'sku_5124922a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Annual',
        price: { startDate: '2024-01-01', endDate: '2024-12-31', pricePoints: [
          { currencyCode: 'USD', amount: 1199 }, { currencyCode: 'EUR', amount: 1103.07 }, { currencyCode: 'JPY', amount: 188243 }, { currencyCode: 'GBP', amount: 947.21 }, { currencyCode: 'AUD', amount: 1798.5 }, { currencyCode: 'CAD', amount: 1642.63 }, { currencyCode: 'CHF', amount: 1079.1 }, { currencyCode: 'CNY', amount: 8692.75 }, { currencyCode: 'HKD', amount: 9352.2 }, { currencyCode: 'NZD', amount: 1954.37 }, { currencyCode: 'SEK', amount: 12529.55 }, { currencyCode: 'KRW', amount: 1650943 }, { currencyCode: 'SGD', amount: 1618.65 }, { currencyCode: 'NOK', amount: 12625.47 }, { currencyCode: 'MXN', amount: 20538.87 }, { currencyCode: 'INR', amount: 100116.5 }, { currencyCode: 'RUB', amount: 107910 }, { currencyCode: 'ZAR', amount: 22421.3 }, { currencyCode: 'TRY', amount: 38607.8 }, { currencyCode: 'BRL', amount: 6174.85 }, { currencyCode: 'TWD', amount: 38721.7 }, { currencyCode: 'DKK', amount: 8249.12 }, { currencyCode: 'PLN', amount: 4736.05 }, { currencyCode: 'THB', amount: 44003.3 }, { currencyCode: 'IDR', amount: 19492143 }, { currencyCode: 'HUF', amount: 429000 }, { currencyCode: 'CZK', amount: 27337.2 }, { currencyCode: 'ILS', amount: 4436.3 }, { currencyCode: 'CLP', amount: 1109075 }, { currencyCode: 'PHP', amount: 70381.3 }, { currencyCode: 'AED', amount: 4400.33 }, { currencyCode: 'COP', amount: 4697682 }, { currencyCode: 'SAR', amount: 4496.25 }, { currencyCode: 'MYR', amount: 5635.3 }, { currencyCode: 'RON', amount: 5515.4 }, { currencyCode: 'ARS', amount: 1075503 }, { currencyCode: 'BDT', amount: 140283 }, { currencyCode: 'VND', amount: 30522943 }, { currencyCode: 'UAH', amount: 48559.5 }, { currencyCode: 'QAR', amount: 4364.36 }, { currencyCode: 'KZT', amount: 535953 }, { currencyCode: 'EGP', amount: 57076.4 }, { currencyCode: 'PKR', amount: 333322 }, { currencyCode: 'OMR', amount: 455.62 }, { currencyCode: 'LKR', amount: 360899 }, { currencyCode: 'NGN', amount: 1774520 }, { currencyCode: 'IQD', amount: 1569491 }, { currencyCode: 'DZD', amount: 160666 }, { currencyCode: 'MAD', amount: 11990 }, { currencyCode: 'PAB', amount: 1199 }, { currencyCode: 'PEN', amount: 4496.25 }, { currencyCode: 'UYU', amount: 46761 }, { currencyCode: 'VEF', amount: 4340080500 }, { currencyCode: 'CRC', amount: 613888 }
        ] },
        revenueRecognition: 'Accrual',
        switcherLogic: [],
        refundPolicy: { id: 'YES_MANUAL', description: 'Yes (the field sales rep can decide)' },
        taxClass: 'Taxable (US Specific)',
      },
    ],
  },
  {
    id: '5095285',
    name: 'Premium Career',
    description: 'Get exclusive access to insights, job search tools, and direct messaging to reach the right people to grow your career.',
    lob: 'Premium',
    category: 'Premium Generic Products',
    status: 'Active',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://www.linkedin.com/premium/career/',
    seatType: 'Single seat',
    isBundle: false,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 0,
    paymentFailurePaidToPaidGracePeriod: 7,
    seatMin: 1,
    seatMax: 1,
    digitalGoods: ['Applicant Insights', '5 InMail Messages/month', 'Resume Insights'],
    tags: [{ type: 'Customer Type', value: 'Individual member' }, { type: 'Sales Top of Funnel', value: 'Premium Chooser' }],
    isVisibleOnBillingEmails: true,
    isVisibleOnRenewalEmails: true,
    isCancellable: true,
    isEligibleForRoboRefund: true,
    isPrimaryProductForPricing: true,
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/lsa',
    productUrl: 'https://www.linkedin.com/premium/career',
    helpCenterUrl: 'https://www.linkedin.com/help/linkedin',
    skus: [
      {
        id: 'sku_5095285a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        price: { startDate: '2024-01-01', pricePoints: [
          { currencyCode: 'USD', amount: 39.99 }, { currencyCode: 'EUR', amount: 36.79 }, { currencyCode: 'JPY', amount: 6278.43 }, { currencyCode: 'GBP', amount: 31.59 }, { currencyCode: 'AUD', amount: 59.99 }, { currencyCode: 'CAD', amount: 54.79 }, { currencyCode: 'CHF', amount: 35.99 }, { currencyCode: 'CNY', amount: 289.93 }, { currencyCode: 'HKD', amount: 311.92 }, { currencyCode: 'NZD', amount: 65.18 }, { currencyCode: 'SEK', amount: 417.89 }, { currencyCode: 'KRW', amount: 55066.23 }, { currencyCode: 'SGD', amount: 53.99 }, { currencyCode: 'NOK', amount: 421.1 }, { currencyCode: 'MXN', amount: 685.08 }, { currencyCode: 'INR', amount: 3339.17 }, { currencyCode: 'RUB', amount: 3599.1 }, { currencyCode: 'ZAR', amount: 747.81 }, { currencyCode: 'TRY', amount: 1287.68 }, { currencyCode: 'BRL', amount: 205.95 }, { currencyCode: 'TWD', amount: 1290.07 }, { currencyCode: 'DKK', amount: 275.13 }, { currencyCode: 'PLN', amount: 157.96 }, { currencyCode: 'THB', amount: 1467.93 }, { currencyCode: 'IDR', amount: 650517.43 }, { currencyCode: 'HUF', amount: 14320.00 }, { currencyCode: 'CZK', amount: 911.77 }, { currencyCode: 'ILS', amount: 147.96 }, { currencyCode: 'CLP', amount: 36965.75 }, { currencyCode: 'PHP', amount: 2347.41 }, { currencyCode: 'AED', amount: 146.79 }, { currencyCode: 'COP', amount: 156563.82 }, { currencyCode: 'SAR', amount: 149.96 }, { currencyCode: 'MYR', amount: 187.95 }, { currencyCode: 'RON', amount: 183.95 }, { currencyCode: 'ARS', amount: 35871.03 }, { currencyCode: 'BDT', amount: 4678.83 }, { currencyCode: 'VND', amount: 1017812.43 }, { currencyCode: 'UAH', amount: 1619.6 }, { currencyCode: 'QAR', amount: 145.56 }, { currencyCode: 'KZT', amount: 17859.63 }, { currencyCode: 'EGP', amount: 1903.52 }, { currencyCode: 'PKR', amount: 11117.22 }, { currencyCode: 'OMR', amount: 15.19 }, { currencyCode: 'LKR', amount: 12036.99 }, { currencyCode: 'NGN', amount: 59185.2 }, { currencyCode: 'IQD', amount: 52346.91 }, { currencyCode: 'DZD', amount: 5358.66 }, { currencyCode: 'MAD', amount: 399.9 }, { currencyCode: 'PAB', amount: 39.99 }, { currencyCode: 'PEN', amount: 149.96 }, { currencyCode: 'UYU', amount: 1559.61 }, { currencyCode: 'VEF', amount: 144680000 }, { currencyCode: 'CRC', amount: 20474.88 }
        ] },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [{ type: 'Upgrade', targetProductId: '5095295' }],
        refundPolicy: { id: 'YES_AUTOMATED', description: 'Yes (automated/robo-refund)' },
      },
      {
        id: 'sku_5095285b',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Annual',
        price: { startDate: '2024-01-01', pricePoints: [
          { currencyCode: 'USD', amount: 399 }, { currencyCode: 'EUR', amount: 367.08 }, { currencyCode: 'JPY', amount: 62643 }, { currencyCode: 'GBP', amount: 315.21 }, { currencyCode: 'AUD', amount: 598.5 }, { currencyCode: 'CAD', amount: 546.63 }, { currencyCode: 'CHF', amount: 359.1 }, { currencyCode: 'CNY', amount: 2892.75 }, { currencyCode: 'HKD', amount: 3112.2 }, { currencyCode: 'NZD', amount: 650.37 }, { currencyCode: 'SEK', amount: 4169.55 }, { currencyCode: 'KRW', amount: 549423 }, { currencyCode: 'SGD', amount: 538.65 }, { currencyCode: 'NOK', amount: 4199.47 }, { currencyCode: 'MXN', amount: 6833.87 }, { currencyCode: 'INR', amount: 33316.5 }, { currencyCode: 'RUB', amount: 35910 }, { currencyCode: 'ZAR', amount: 7461.3 }, { currencyCode: 'TRY', amount: 12847.8 }, { currencyCode: 'BRL', amount: 2054.85 }, { currencyCode: 'TWD', amount: 12870.7 }, { currencyCode: 'DKK', amount: 2744.22 }, { currencyCode: 'PLN', amount: 1575.05 }, { currencyCode: 'THB', amount: 14640.3 }, { currencyCode: 'IDR', amount: 6490257 }, { currencyCode: 'HUF', amount: 142800 }, { currencyCode: 'CZK', amount: 9094.8 }, { currencyCode: 'ILS', amount: 1476.3 }, { currencyCode: 'CLP', amount: 368725 }, { currencyCode: 'PHP', amount: 23415.3 }, { currencyCode: 'AED', amount: 1464.03 }, { currencyCode: 'COP', amount: 1562018 }, { currencyCode: 'SAR', amount: 1496.25 }, { currencyCode: 'MYR', amount: 1875.3 }, { currencyCode: 'RON', amount: 1835.4 }, { currencyCode: 'ARS', amount: 357803 }, { currencyCode: 'BDT', amount: 46683 }, { currencyCode: 'VND', amount: 10153457 }, { currencyCode: 'UAH', amount: 16159.5 }, { currencyCode: 'QAR', amount: 1452.36 }, { currencyCode: 'KZT', amount: 178153 }, { currencyCode: 'EGP', amount: 18991.4 }, { currencyCode: 'PKR', amount: 110882 }, { currencyCode: 'OMR', amount: 151.62 }, { currencyCode: 'LKR', amount: 120099 }, { currencyCode: 'NGN', amount: 590520 }, { currencyCode: 'IQD', amount: 522291 }, { currencyCode: 'DZD', amount: 53466 }, { currencyCode: 'MAD', amount: 3990 }, { currencyCode: 'PAB', amount: 399 }, { currencyCode: 'PEN', amount: 1496.25 }, { currencyCode: 'UYU', amount: 15561 }, { currencyCode: 'VEF', amount: 144360000 }, { currencyCode: 'CRC', amount: 204288 }
        ] },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [{ type: 'Upgrade', targetProductId: '5095295' }],
        refundPolicy: { id: 'YES_AUTOMATED', description: 'Yes (automated/robo-refund)' },
        lix: {
          key: 'career-annual-price-test',
          treatment: 'treatment-a',
        },
      },
    ],
  },
  {
    id: '5095295',
    name: 'Premium Business',
    description: 'Get exclusive access to insights, search tools, and direct messaging to reach the right people to grow your business.',
    lob: 'Premium',
    category: 'Premium Generic Products',
    status: 'Active',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://www.linkedin.com/premium/business/',
    seatType: 'Single seat',
    isBundle: false,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 7,
    paymentFailurePaidToPaidGracePeriod: 14,
    seatMin: 1,
    seatMax: 1,
    digitalGoods: ['Business Insights', '15 InMail Messages/month', 'Unlimited Searches'],
    tags: [{ type: 'Customer Type', value: 'Individual member' }],
    isCancellable: false,
    isPrimaryForGracePeriod: true,
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/lsa',
    productUrl: 'https://www.linkedin.com/premium/business',
    skus: [
      {
        id: 'sku_5095295a',
        status: 'Active',
        region: 'EMEA',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        price: { 
          startDate: '2024-01-01', 
          pricePoints: [
            { currencyCode: 'USD', amount: 59.99 }, { currencyCode: 'EUR', amount: 49.99 }, { currencyCode: 'JPY', amount: 9418.43 }, { currencyCode: 'GBP', amount: 47.39 }, { currencyCode: 'AUD', amount: 89.99 }, { currencyCode: 'CAD', amount: 82.19 }, { currencyCode: 'CHF', amount: 53.99 }, { currencyCode: 'CNY', amount: 434.93 }, { currencyCode: 'HKD', amount: 467.92 }, { currencyCode: 'NZD', amount: 97.78 }, { currencyCode: 'SEK', amount: 626.89 }, { currencyCode: 'KRW', amount: 82599.23 }, { currencyCode: 'SGD', amount: 80.99 }, { currencyCode: 'NOK', amount: 631.6 }, { currencyCode: 'MXN', amount: 1027.62 }, { currencyCode: 'INR', amount: 5008.17 }, { currencyCode: 'RUB', amount: 5399.1 }, { currencyCode: 'ZAR', amount: 1121.81 }, { currencyCode: 'TRY', amount: 1931.68 }, { currencyCode: 'BRL', amount: 308.95 }, { currencyCode: 'TWD', amount: 1935.07 }, { currencyCode: 'DKK', amount: 412.63 }, { currencyCode: 'PLN', amount: 236.96 }, { currencyCode: 'THB', amount: 2201.93 }, { currencyCode: 'IDR', amount: 975857.43 }, { currencyCode: 'HUF', amount: 21480.00 }, { currencyCode: 'CZK', amount: 1367.77 }, { currencyCode: 'ILS', amount: 221.96 }, { currencyCode: 'CLP', amount: 55448.75 }, { currencyCode: 'PHP', amount: 3521.41 }, { currencyCode: 'AED', amount: 220.19 }, { currencyCode: 'COP', amount: 234863.82 }, { currencyCode: 'SAR', amount: 224.96 }, { currencyCode: 'MYR', amount: 281.95 }, { currencyCode: 'RON', amount: 275.95 }, { currencyCode: 'ARS', amount: 53811.03 }, { currencyCode: 'BDT', amount: 7018.83 }, { currencyCode: 'VND', amount: 1526812.43 }, { currencyCode: 'UAH', amount: 2429.6 }, { currencyCode: 'QAR', amount: 218.36 }, { currencyCode: 'KZT', amount: 26790.63 }, { currencyCode: 'EGP', amount: 2855.52 }, { currencyCode: 'PKR', amount: 16677.22 }, { currencyCode: 'OMR', amount: 22.79 }, { currencyCode: 'LKR', amount: 18056.99 }, { currencyCode: 'NGN', amount: 88785.2 }, { currencyCode: 'IQD', amount: 78526.91 }, { currencyCode: 'DZD', amount: 8038.66 }, { currencyCode: 'MAD', amount: 599.9 }, { currencyCode: 'PAB', amount: 59.99 }, { currencyCode: 'PEN', amount: 224.96 }, { currencyCode: 'UYU', amount: 2339.61 }, { currencyCode: 'VEF', amount: 217040000 }, { currencyCode: 'CRC', amount: 30714.88 }
          ] 
        },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [{ type: 'Downgrade', targetProductId: '5095285' }],
        refundPolicy: { id: 'YES_AUTOMATED', description: 'Yes (automated/robo-refund)' },
      },
    ],
  },
  {
    id: '5083684',
    name: 'Recruiter Lite',
    description: 'Find the right talent faster. Search for qualified candidates with 20+ filters, 30 InMail messages per month, saved search alerts, daily candidate recommendations, among other features.',
    lob: 'LTS',
    category: 'RLite',
    status: 'Active',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://www.linkedin.com/talent/recruiter-lite/',
    seatType: 'Single seat',
    isBundle: true,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 7,
    paymentFailurePaidToPaidGracePeriod: 7,
    seatMin: 1,
    seatMax: 1,
    digitalGoods: ['20+ Search Filters', '30 InMail Messages/month', 'Candidate Recommendations'],
    tags: [{ type: 'Customer Type', value: 'Enterprise customer' }],
    isCancellable: true,
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/lsa',
    productUrl: 'https://www.linkedin.com/talent/recruiter-lite',
    skus: [
       {
        id: 'sku_5083684a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        price: { startDate: '2024-01-01', pricePoints: [
          { currencyCode: 'USD', amount: 169.95 }, { currencyCode: 'EUR', amount: 156.35 }, { currencyCode: 'JPY', amount: 26682.15 }, { currencyCode: 'GBP', amount: 134.26 }, { currencyCode: 'AUD', amount: 254.93 }, { currencyCode: 'CAD', amount: 232.83 }, { currencyCode: 'CHF', amount: 152.96 }, { currencyCode: 'CNY', amount: 1232.14 }, { currencyCode: 'HKD', amount: 1325.61 }, { currencyCode: 'NZD', amount: 277.02 }, { currencyCode: 'SEK', amount: 1775.98 }, { currencyCode: 'KRW', amount: 233991.15 }, { currencyCode: 'SGD', amount: 229.43 }, { currencyCode: 'NOK', amount: 1790.31 }, { currencyCode: 'MXN', amount: 2911.28 }, { currencyCode: 'INR', amount: 14189.33 }, { currencyCode: 'RUB', amount: 15295.5 }, { currencyCode: 'ZAR', amount: 3177.07 }, { currencyCode: 'TRY', amount: 5472.39 }, { currencyCode: 'BRL', amount: 875.24 }, { currencyCode: 'TWD', amount: 5491.87 }, { currencyCode: 'DKK', amount: 1170.21 }, { currencyCode: 'PLN', amount: 671.3 }, { currencyCode: 'THB', amount: 6241.37 }, { currencyCode: 'IDR', amount: 2765373.15 }, { currencyCode: 'HUF', amount: 60980.00 }, { currencyCode: 'CZK', amount: 3878.86 }, { currencyCode: 'ILS', amount: 628.82 }, { currencyCode: 'CLP', amount: 157203.75 }, { currencyCode: 'PHP', amount: 9976.67 }, { currencyCode: 'AED', amount: 624.14 }, { currencyCode: 'COP', amount: 666750.3 }, { currencyCode: 'SAR', amount: 637.31 }, { currencyCode: 'MYR', amount: 798.77 }, { currencyCode: 'RON', amount: 781.77 }, { currencyCode: 'ARS', amount: 152479.65 }, { currencyCode: 'BDT', amount: 19884.15 }, { currencyCode: 'VND', amount: 4325493.15 }, { currencyCode: 'UAH', amount: 6883.0 }, { currencyCode: 'QAR', amount: 618.92 }, { currencyCode: 'KZT', amount: 75990.15 }, { currencyCode: 'EGP', amount: 8089.53 }, { currencyCode: 'PKR', amount: 47252.1 }, { currencyCode: 'OMR', amount: 64.58 }, { currencyCode: 'LKR', amount: 51154.95 }, { currencyCode: 'NGN', amount: 251526.0 }, { currencyCode: 'IQD', amount: 222564.45 }, { currencyCode: 'DZD', amount: 22773.3 }, { currencyCode: 'MAD', amount: 1699.5 }, { currencyCode: 'PAB', amount: 169.95 }, { currencyCode: 'PEN', amount: 637.31 }, { currencyCode: 'UYU', amount: 6628.05 }, { currencyCode: 'VEF', amount: 615100000 }, { currencyCode: 'CRC', amount: 87014.4 }
        ] },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [],
        refundPolicy: { id: 'NO_CREDIT', description: 'No (field sales rep can however give customer a credit toward next invoice)' },
      },
       {
        id: 'sku_5083684b',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Annual',
        price: { startDate: '2024-01-01', pricePoints: [
          { currencyCode: 'USD', amount: 1680 }, { currencyCode: 'EUR', amount: 1545.6 }, { currencyCode: 'JPY', amount: 263760 }, { currencyCode: 'GBP', amount: 1327.2 }, { currencyCode: 'AUD', amount: 2520 }, { currencyCode: 'CAD', amount: 2301.6 }, { currencyCode: 'CHF', amount: 1512 }, { currencyCode: 'CNY', amount: 12180 }, { currencyCode: 'HKD', amount: 13104 }, { currencyCode: 'NZD', amount: 2738.4 }, { currencyCode: 'SEK', amount: 17556 }, { currencyCode: 'KRW', amount: 2313360 }, { currencyCode: 'SGD', amount: 2268 }, { currencyCode: 'NOK', amount: 17690.4 }, { currencyCode: 'MXN', amount: 28778.4 }, { currencyCode: 'INR', amount: 140280 }, { currencyCode: 'RUB', amount: 151200 }, { currencyCode: 'ZAR', amount: 31416 }, { currencyCode: 'TRY', amount: 54096 }, { currencyCode: 'BRL', amount: 8652 }, { currencyCode: 'TWD', amount: 54264 }, { currencyCode: 'DKK', amount: 11558.4 }, { currencyCode: 'PLN', amount: 6636 }, { currencyCode: 'THB', amount: 61656 }, { currencyCode: 'IDR', amount: 27311760 }, { currencyCode: 'HUF', amount: 603100 }, { currencyCode: 'CZK', amount: 38304 }, { currencyCode: 'ILS', amount: 6216 }, { currencyCode: 'CLP', amount: 1554000 }, { currencyCode: 'PHP', amount: 98616 }, { currencyCode: 'AED', amount: 6165.6 }, { currencyCode: 'COP', amount: 6582160 }, { currencyCode: 'SAR', amount: 6300 }, { currencyCode: 'MYR', amount: 7896 }, { currencyCode: 'RON', amount: 7728 }, { currencyCode: 'ARS', amount: 1506960 }, { currencyCode: 'BDT', amount: 196560 }, { currencyCode: 'VND', amount: 42767760 }, { currencyCode: 'UAH', amount: 68040 }, { currencyCode: 'QAR', amount: 6115.2 }, { currencyCode: 'KZT', amount: 750960 }, { currencyCode: 'EGP', amount: 79968 }, { currencyCode: 'PKR', amount: 467040 }, { currencyCode: 'OMR', amount: 638.4 }, { currencyCode: 'LKR', amount: 505680 }, { currencyCode: 'NGN', amount: 2494800 }, { currencyCode: 'IQD', amount: 2201280 }, { currencyCode: 'DZD', amount: 225120 }, { currencyCode: 'MAD', amount: 16800 }, { currencyCode: 'PAB', amount: 1680 }, { currencyCode: 'PEN', amount: 6300 }, { currencyCode: 'UYU', amount: 65520 }, { currencyCode: 'VEF', amount: 6081600000 }, { currencyCode: 'CRC', amount: 860160 }
        ] },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [],
        refundPolicy: { id: 'NO_CREDIT', description: 'No (field sales rep can however give customer a credit toward next invoice)' },
      }
    ],
  },
  {
    id: '5073467',
    name: 'Sales Navigator Advanced',
    description: 'Forge deeper relationships by leveraging real-time sales intelligence and seamless collaboration with your team.',
    lob: 'LSS',
    category: 'Sales Navigator',
    status: 'Active',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://www.linkedin.com/sales/',
    seatType: 'Multi-seat enterprise',
    isBundle: true,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 30,
    paymentFailurePaidToPaidGracePeriod: 30,
    seatMin: 5,
    seatMax: 100,
    digitalGoods: ['TeamLink', '50 InMail Messages/month', 'Buyer Interest'],
    tags: [{ type: 'Customer Type', value: 'Enterprise customer' }, { type: 'Contract Type', value: 'Fixed time' }],
    isPrimaryForContractAggregation: true,
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/lsa',
    productUrl: 'https://www.linkedin.com/sales/',
    contactUsUrl: 'https://www.linkedin.com/help/linkedin/ask/li-salesnav',
    skus: [
      {
        id: 'sku_5073467a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Field',
        billingCycle: 'Annual',
        price: { startDate: '2024-01-01', pricePoints: [
          { currencyCode: 'USD', amount: 1600 }, { currencyCode: 'CAD', amount: 2192 }, { currencyCode: 'GBP', amount: 1264 }, { currencyCode: 'EUR', amount: 1472 }, { currencyCode: 'AUD', amount: 2400 }, { currencyCode: 'SGD', amount: 2160 }, { currencyCode: 'INR', amount: 133600 }, { currencyCode: 'HKD', amount: 12480 }, { currencyCode: 'CNY', amount: 11600 }, { currencyCode: 'JPY', amount: 251200 }
        ] },
        revenueRecognition: 'Accrual',
        switcherLogic: [],
        refundPolicy: { id: 'NO_CREDIT', description: 'No (field sales rep can however give customer a credit toward next invoice)' },
      },
    ],
  },
  {
    id: '5095305',
    name: 'Sales Navigator Core',
    description: 'Build trusted relationships by using the power of LinkedIn data to find, research, and communicate with customers/prospects.',
    lob: 'LSS',
    category: 'Sales Navigator',
    status: 'Active',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://www.linkedin.com/sales/core',
    seatType: 'Single seat',
    isBundle: false,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 7,
    paymentFailurePaidToPaidGracePeriod: 7,
    seatMin: 1,
    seatMax: 1,
    digitalGoods: ['Core Sales Nav Features', '50 InMail Messages/month'],
    tags: [{ type: 'Customer Type', value: 'Individual member' }, { type: 'Sales Top of Funnel', value: 'Web CTA' }],
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/lsa',
    productUrl: 'https://www.linkedin.com/sales/core',
    skus: [
      {
        id: 'sku_5095305a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Annual',
        price: { startDate: '2024-01-01', pricePoints: [
          { currencyCode: 'USD', amount: 959 }, { currencyCode: 'EUR', amount: 882.28 }, { currencyCode: 'JPY', amount: 150563 }, { currencyCode: 'GBP', amount: 757.61 }, { currencyCode: 'AUD', amount: 1438.5 }, { currencyCode: 'CAD', amount: 1313.83 }, { currencyCode: 'CHF', amount: 863.1 }, { currencyCode: 'CNY', amount: 6952.75 }, { currencyCode: 'HKD', amount: 7480.2 }, { currencyCode: 'NZD', amount: 1563.17 }, { currencyCode: 'SEK', amount: 10021.55 }, { currencyCode: 'KRW', amount: 1320000 }, { currencyCode: 'SGD', amount: 1294.65 }, { currencyCode: 'NOK', amount: 10098.87 }, { currencyCode: 'MXN', amount: 16428.07 }, { currencyCode: 'INR', amount: 80076.5 }, { currencyCode: 'RUB', amount: 86310 }, { currencyCode: 'ZAR', amount: 17933.3 }, { currencyCode: 'TRY', amount: 30879.8 }, { currencyCode: 'BRL', amount: 4938.85 }, { currencyCode: 'TWD', amount: 30987.7 }, { currencyCode: 'DKK', amount: 6606.32 }, { currencyCode: 'PLN', amount: 3788.05 }, { currencyCode: 'THB', amount: 35167.3 }, { currencyCode: 'IDR', amount: 15582963 }, { currencyCode: 'HUF', amount: 344300 }, { currencyCode: 'CZK', amount: 21829.2 }, { currencyCode: 'ILS', amount: 3548.3 }, { currencyCode: 'CLP', amount: 887075 }, { currencyCode: 'PHP', amount: 56325.3 }, { currencyCode: 'AED', amount: 3516.73 }, { currencyCode: 'COP', amount: 3757822 }, { currencyCode: 'SAR', amount: 3596.25 }, { currencyCode: 'MYR', amount: 4507.3 }, { currencyCode: 'RON', amount: 4411.4 }, { currencyCode: 'ARS', amount: 860223 }, { currencyCode: 'BDT', amount: 112203 }, { currencyCode: 'VND', amount: 24419963 }, { currencyCode: 'UAH', amount: 38839.5 }, { currencyCode: 'QAR', amount: 3491.16 }, { currencyCode: 'KZT', amount: 428773 }, { currencyCode: 'EGP', amount: 45648.4 }, { currencyCode: 'PKR', amount: 266962 }, { currencyCode: 'OMR', amount: 364.42 }, { currencyCode: 'LKR', amount: 288659 }, { currencyCode: 'NGN', amount: 1419720 }, { currencyCode: 'IQD', amount: 1255889 }, { currencyCode: 'DZD', amount: 128506 }, { currencyCode: 'MAD', amount: 9590 }, { currencyCode: 'PAB', amount: 959 }, { currencyCode: 'PEN', amount: 3596.25 }, { currencyCode: 'UYU', amount: 37401 }, { currencyCode: 'VEF', amount: 3471000000 }, { currencyCode: 'CRC', amount: 490992 }
        ] },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [{type: 'Upgrade', targetProductId: '5073467'}],
        refundPolicy: { id: 'YES_AUTOMATED', description: 'Yes (automated/robo-refund)' },
      },
      {
        id: 'sku_5095305b',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        price: { startDate: '2024-01-01', pricePoints: [
          { currencyCode: 'USD', amount: 99.99 }, { currencyCode: 'EUR', amount: 91.99 }, { currencyCode: 'JPY', amount: 15698.43 }, { currencyCode: 'GBP', amount: 78.99 }, { currencyCode: 'AUD', amount: 149.99 }, { currencyCode: 'CAD', amount: 136.99 }, { currencyCode: 'CHF', amount: 89.99 }, { currencyCode: 'CNY', amount: 724.93 }, { currencyCode: 'HKD', amount: 779.92 }, { currencyCode: 'NZD', amount: 162.98 }, { currencyCode: 'SEK', amount: 1044.89 }, { currencyCode: 'KRW', amount: 137700.23 }, { currencyCode: 'SGD', amount: 134.99 }, { currencyCode: 'NOK', amount: 1052.89 }, { currencyCode: 'MXN', amount: 1712.87 }, { currencyCode: 'INR', amount: 8349.17 }, { currencyCode: 'RUB', amount: 8999.1 }, { currencyCode: 'ZAR', amount: 1869.13 }, { currencyCode: 'TRY', amount: 3219.68 }, { currencyCode: 'BRL', amount: 514.95 }, { currencyCode: 'TWD', amount: 3229.67 }, { currencyCode: 'DKK', amount: 687.93 }, { currencyCode: 'PLN', amount: 394.96 }, { currencyCode: 'THB', amount: 3669.63 }, { currencyCode: 'IDR', amount: 1625537.43 }, { currencyCode: 'HUF', amount: 35900.00 }, { currencyCode: 'CZK', amount: 2280.00 }, { currencyCode: 'ILS', amount: 369.96 }, { currencyCode: 'CLP', amount: 92477.75 }, { currencyCode: 'PHP', amount: 5869.41 }, { currencyCode: 'AED', amount: 366.96 }, { currencyCode: 'COP', amount: 391408.82 }, { currencyCode: 'SAR', amount: 374.96 }, { currencyCode: 'MYR', amount: 469.95 }, { currencyCode: 'RON', amount: 459.95 }, { currencyCode: 'ARS', amount: 89691.03 }, { currencyCode: 'BDT', amount: 11698.83 }, { currencyCode: 'VND', amount: 2544702.43 }, { currencyCode: 'UAH', amount: 4049.6 }, { currencyCode: 'QAR', amount: 363.96 }, { currencyCode: 'KZT', amount: 44690.63 }, { currencyCode: 'EGP', amount: 4759.52 }, { currencyCode: 'PKR', amount: 27797.22 }, { currencyCode: 'OMR', amount: 37.99 }, { currencyCode: 'LKR', amount: 30096.99 }, { currencyCode: 'NGN', amount: 148485.2 }, { currencyCode: 'IQD', amount: 130886.91 }, { currencyCode: 'DZD', amount: 13398.66 }, { currencyCode: 'MAD', amount: 999.9 }, { currencyCode: 'PAB', amount: 99.99 }, { currencyCode: 'PEN', amount: 374.96 }, { currencyCode: 'UYU', amount: 3899.61 }, { currencyCode: 'VEF', amount: 361880000 }, { currencyCode: 'CRC', amount: 51194.88 }
        ] },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [{type: 'Upgrade', targetProductId: '5073467'}],
        refundPolicy: { id: 'YES_AUTOMATED', description: 'Yes (automated/robo-refund)' },
        lix: {
          key: 'sales-nav-core-monthly-v2',
          treatment: 'control',
        },
      },
    ],
  },
  {
    id: '5138141',
    name: 'LinkedIn Learning for Business',
    description: 'Provide your entire organization with unlimited access to over 16,000 expert-led courses.',
    lob: 'LTS',
    category: 'Learning',
    status: 'Active',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://learning.linkedin.com/for-business',
    seatType: 'Multi-seat enterprise',
    isBundle: true,
    taxClass: 'Varies by region',
    paymentFailureFreeToPaidGracePeriod: 14,
    paymentFailurePaidToPaidGracePeriod: 14,
    seatMin: 2,
    seatMax: 1000,
    digitalGoods: ['Full Course Catalog', 'Admin Analytics', 'Learning Paths'],
    isCancellable: true,
    termsOfServiceUrl: 'https://learning.linkedin.com/legal-terms',
    productUrl: 'https://learning.linkedin.com/for-business',
    skus: [
      {
        id: 'sku_5138141a',
        status: 'Active',
        region: 'EMEA',
        salesChannel: 'Field',
        billingCycle: 'Annual',
        price: {
          pricePoints: [
            { currencyCode: 'USD', amount: 2400 }, { currencyCode: 'CAD', amount: 3288 }, { currencyCode: 'GBP', amount: 1896 }, { currencyCode: 'EUR', amount: 2208 }, { currencyCode: 'AUD', amount: 3600 }, { currencyCode: 'SGD', amount: 3240 }, { currencyCode: 'INR', amount: 200400 }, { currencyCode: 'HKD', amount: 18720 }, { currencyCode: 'CNY', amount: 17400 }, { currencyCode: 'JPY', amount: 376800 }
          ]
        },
        revenueRecognition: 'Accrual',
        switcherLogic: [],
        refundPolicy: { id: 'NO_CREDIT', description: 'No (field sales rep can however give customer a credit toward next invoice)' },
      }
    ],
  },
  {
    id: '5102113',
    name: 'LinkedIn Ads - Sponsored Content',
    description: 'Promote your company updates to targeted audiences on desktop, mobile, and tablet.',
    lob: 'LMS',
    category: 'Ads',
    status: 'Active',
    billingModel: 'Usage',
    postPurchaseLandingUrl: 'https://business.linkedin.com/marketing-solutions/ads',
    seatType: 'Single seat',
    isBundle: false,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 0,
    paymentFailurePaidToPaidGracePeriod: 0,
    seatMin: 1,
    seatMax: 1,
    digitalGoods: ['Ad Campaign Management'],
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/ads-terms',
    productUrl: 'https://business.linkedin.com/marketing-solutions/ads',
    skus: [
      {
        id: 'sku_5102113a',
        status: 'Active',
        region: 'APAC',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        price: {
          pricePoints: [
            { currencyCode: 'USD', amount: 500 }, { currencyCode: 'EUR', amount: 460 }, { currencyCode: 'JPY', amount: 78500 }, { currencyCode: 'GBP', amount: 395 }, { currencyCode: 'AUD', amount: 750 }, { currencyCode: 'CAD', amount: 685 }, { currencyCode: 'CHF', amount: 450 }, { currencyCode: 'CNY', amount: 3625 }, { currencyCode: 'HKD', amount: 3900 }, { currencyCode: 'NZD', amount: 815 }, { currencyCode: 'SEK', amount: 5225 }, { currencyCode: 'KRW', amount: 688500 }, { currencyCode: 'SGD', amount: 675 }, { currencyCode: 'NOK', amount: 5265 }, { currencyCode: 'MXN', amount: 8565 }, { currencyCode: 'INR', amount: 41750 }, { currencyCode: 'RUB', amount: 45000 }, { currencyCode: 'ZAR', amount: 9350 }, { currencyCode: 'TRY', amount: 16100 }, { currencyCode: 'BRL', amount: 2575 }, { currencyCode: 'TWD', amount: 16150 }, { currencyCode: 'DKK', amount: 3440 }, { currencyCode: 'PLN', amount: 1975 }, { currencyCode: 'THB', amount: 18350 }, { currencyCode: 'IDR', amount: 8128500 }, { currencyCode: 'HUF', amount: 179500 }, { currencyCode: 'CZK', amount: 11400 }, { currencyCode: 'ILS', amount: 1850 }, { currencyCode: 'CLP', amount: 462500 }, { currencyCode: 'PHP', amount: 29350 }, { currencyCode: 'AED', amount: 1835 }, { currencyCode: 'COP', amount: 1959000 }, { currencyCode: 'SAR', amount: 1875 }, { currencyCode: 'MYR', amount: 2350 }, { currencyCode: 'RON', amount: 2300 }, { currencyCode: 'ARS', amount: 448500 }, { currencyCode: 'BDT', amount: 58500 }, { currencyCode: 'VND', amount: 12728500 }, { currencyCode: 'UAH', amount: 20250 }, { currencyCode: 'QAR', amount: 1820 }, { currencyCode: 'KZT', amount: 223500 }, { currencyCode: 'EGP', amount: 23800 }, { currencyCode: 'PKR', amount: 139000 }, { currencyCode: 'OMR', amount: 190 }, { currencyCode: 'LKR', amount: 150500 }, { currencyCode: 'NGN', amount: 740000 }, { currencyCode: 'IQD', amount: 654500 }, { currencyCode: 'DZD', amount: 67000 }, { currencyCode: 'MAD', amount: 5000 }, { currencyCode: 'PAB', amount: 500 }, { currencyCode: 'PEN', amount: 1875 }, { currencyCode: 'UYU', amount: 19500 }, { currencyCode: 'VEF', amount: 1809250000 }, { currencyCode: 'CRC', amount: 256000 }
          ]
        },
        revenueRecognition: 'On invoicing',
        switcherLogic: [],
        refundPolicy: { id: 'YES_TAX_ONLY', description: 'Yes (only for applicable taxes)' },
      }
    ],
  },
  {
    id: '5099987',
    name: 'Glint Employee Engagement',
    description: 'Understand and improve employee engagement with real-time data and insights.',
    lob: 'LTS',
    category: 'Glint',
    status: 'Legacy',
    billingModel: 'Subscription',
    postPurchaseLandingUrl: 'https://www.glintinc.com/',
    seatType: 'Multi-seat enterprise',
    isBundle: false,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 30,
    paymentFailurePaidToPaidGracePeriod: 30,
    seatMin: 100,
    seatMax: 10000,
    digitalGoods: ['Engagement Surveys', 'Manager Dashboards', 'Action Plans'],
    termsOfServiceUrl: 'https://www.glintinc.com/terms-of-service/',
    productUrl: 'https://www.glintinc.com/',
    skus: [
      {
        id: 'sku_5099987a',
        status: 'Legacy',
        region: 'NAMER',
        salesChannel: 'Field',
        billingCycle: 'Annual',
        price: { pricePoints: [
          { currencyCode: 'USD', amount: 15000 }, { currencyCode: 'CAD', amount: 20550 }, { currencyCode: 'GBP', amount: 11850 }, { currencyCode: 'EUR', amount: 13800 }, { currencyCode: 'AUD', amount: 22500 }, { currencyCode: 'SGD', amount: 20250 }, { currencyCode: 'INR', amount: 1252500 }, { currencyCode: 'HKD', amount: 117000 }, { currencyCode: 'CNY', amount: 108750 }, { currencyCode: 'JPY', amount: 2355000 }
        ] },
        revenueRecognition: 'Accrual',
        switcherLogic: [],
        refundPolicy: { id: 'NO_CREDIT', description: 'No (field sales rep can however give customer a credit toward next invoice)' },
      }
    ]
  },
  {
    id: '5083690',
    name: 'LinkedIn Jobs - Job Slot',
    description: 'Post a job to reach qualified candidates across the LinkedIn network.',
    lob: 'LTS',
    category: 'Jobs',
    status: 'Active',
    billingModel: 'One-time',
    postPurchaseLandingUrl: 'https://www.linkedin.com/talent/post-a-job',
    seatType: 'Single seat',
    isBundle: false,
    taxClass: 'Taxable',
    paymentFailureFreeToPaidGracePeriod: 0,
    paymentFailurePaidToPaidGracePeriod: 0,
    seatMin: 1,
    seatMax: 1,
    digitalGoods: ['Single Job Posting'],
    termsOfServiceUrl: 'https://www.linkedin.com/legal/l/jobs-terms',
    productUrl: 'https://www.linkedin.com/talent/post-a-job',
    skus: [
      {
        id: 'sku_5083690a',
        status: 'Active',
        region: 'NAMER',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly', // Note: One-time purchase, but cycle can denote duration
        price: { pricePoints: [
          { currencyCode: 'USD', amount: 495 }, { currencyCode: 'EUR', amount: 455.4 }, { currencyCode: 'JPY', amount: 77715 }, { currencyCode: 'GBP', amount: 391.05 }, { currencyCode: 'AUD', amount: 742.5 }, { currencyCode: 'CAD', amount: 678.15 }, { currencyCode: 'CHF', amount: 445.5 }, { currencyCode: 'CNY', amount: 3588.75 }, { currencyCode: 'HKD', amount: 3861 }, { currencyCode: 'NZD', amount: 806.85 }, { currencyCode: 'SEK', amount: 5172.75 }, { currencyCode: 'KRW', amount: 681615 }, { currencyCode: 'SGD', amount: 668.25 }, { currencyCode: 'NOK', amount: 5212.35 }, { currencyCode: 'MXN', amount: 8479.35 }, { currencyCode: 'INR', amount: 41332.5 }, { currencyCode: 'RUB', amount: 44550 }, { currencyCode: 'ZAR', amount: 9256.5 }, { currencyCode: 'TRY', amount: 15939 }, { currencyCode: 'BRL', amount: 2549.25 }, { currencyCode: 'TWD', amount: 15988.5 }, { currencyCode: 'DKK', amount: 3405.6 }, { currencyCode: 'PLN', amount: 1955.25 }, { currencyCode: 'THB', amount: 18166.5 }, { currencyCode: 'IDR', amount: 8047215 }, { currencyCode: 'HUF', amount: 177700 }, { currencyCode: 'CZK', amount: 11286 }, { currencyCode: 'ILS', amount: 1831.5 }, { currencyCode: 'CLP', amount: 458025 }, { currencyCode: 'PHP', amount: 29056.5 }, { currencyCode: 'AED', amount: 1816.65 }, { currencyCode: 'COP', amount: 1939410 }, { currencyCode: 'SAR', amount: 1856.25 }, { currencyCode: 'MYR', amount: 2326.5 }, { currencyCode: 'RON', amount: 2277 }, { currencyCode: 'ARS', amount: 443955 }, { currencyCode: 'BDT', amount: 57915 }, { currencyCode: 'VND', amount: 12601215 }, { currencyCode: 'UAH', amount: 20047.5 }, { currencyCode: 'QAR', amount: 1801.8 }, { currencyCode: 'KZT', amount: 221265 }, { currencyCode: 'EGP', amount: 23562 }, { currencyCode: 'PKR', amount: 137610 }, { currencyCode: 'OMR', amount: 188.1 }, { currencyCode: 'LKR', amount: 148995 }, { currencyCode: 'NGN', amount: 732600 }, { currencyCode: 'IQD', amount: 647955 }, { currencyCode: 'DZD', amount: 66330 }, { currencyCode: 'MAD', amount: 4950 }, { currencyCode: 'PAB', amount: 495 }, { currencyCode: 'PEN', amount: 1856.25 }, { currencyCode: 'UYU', amount: 19305 }, { currencyCode: 'VEF', amount: 1791160000 }, { currencyCode: 'CRC', amount: 253440 }
        ] },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [],
        refundPolicy: { id: 'YES_AUTOMATED', description: 'Yes (automated/robo-refund)' },
      },
      {
        id: 'sku_5083690b',
        status: 'Active',
        region: 'EMEA',
        salesChannel: 'Desktop',
        billingCycle: 'Monthly',
        price: {
          pricePoints: [
            { currencyCode: 'USD', amount: 495 }, { currencyCode: 'EUR', amount: 450 }, { currencyCode: 'JPY', amount: 77715 }, { currencyCode: 'GBP', amount: 391.05 }, { currencyCode: 'AUD', amount: 742.5 }, { currencyCode: 'CAD', amount: 678.15 }, { currencyCode: 'CHF', amount: 445.5 }, { currencyCode: 'CNY', amount: 3588.75 }, { currencyCode: 'HKD', amount: 3861 }, { currencyCode: 'NZD', amount: 806.85 }, { currencyCode: 'SEK', amount: 5172.75 }, { currencyCode: 'KRW', amount: 681615 }, { currencyCode: 'SGD', amount: 668.25 }, { currencyCode: 'NOK', amount: 5212.35 }, { currencyCode: 'MXN', amount: 8479.35 }, { currencyCode: 'INR', amount: 41332.5 }, { currencyCode: 'RUB', amount: 44550 }, { currencyCode: 'ZAR', amount: 9256.5 }, { currencyCode: 'TRY', amount: 15939 }, { currencyCode: 'BRL', amount: 2549.25 }, { currencyCode: 'TWD', amount: 15988.5 }, { currencyCode: 'DKK', amount: 3405.6 }, { currencyCode: 'PLN', amount: 1955.25 }, { currencyCode: 'THB', amount: 18166.5 }, { currencyCode: 'IDR', amount: 8047215 }, { currencyCode: 'HUF', amount: 177700 }, { currencyCode: 'CZK', amount: 11286 }, { currencyCode: 'ILS', amount: 1831.5 }, { currencyCode: 'CLP', amount: 458025 }, { currencyCode: 'PHP', amount: 29056.5 }, { currencyCode: 'AED', amount: 1816.65 }, { currencyCode: 'COP', amount: 1939410 }, { currencyCode: 'SAR', amount: 1856.25 }, { currencyCode: 'MYR', amount: 2326.5 }, { currencyCode: 'RON', amount: 2277 }, { currencyCode: 'ARS', amount: 443955 }, { currencyCode: 'BDT', amount: 57915 }, { currencyCode: 'VND', amount: 12601215 }, { currencyCode: 'UAH', amount: 20047.5 }, { currencyCode: 'QAR', amount: 1801.8 }, { currencyCode: 'KZT', amount: 221265 }, { currencyCode: 'EGP', amount: 23562 }, { currencyCode: 'PKR', amount: 137610 }, { currencyCode: 'OMR', amount: 188.1 }, { currencyCode: 'LKR', amount: 148995 }, { currencyCode: 'NGN', amount: 732600 }, { currencyCode: 'IQD', amount: 647955 }, { currencyCode: 'DZD', amount: 66330 }, { currencyCode: 'MAD', amount: 4950 }, { currencyCode: 'PAB', amount: 495 }, { currencyCode: 'PEN', amount: 1856.25 }, { currencyCode: 'UYU', amount: 19305 }, { currencyCode: 'VEF', amount: 1791160000 }, { currencyCode: 'CRC', amount: 253440 }
          ]
        },
        revenueRecognition: 'On payment receipt',
        switcherLogic: [],
        refundPolicy: { id: 'YES_AUTOMATED', description: 'Yes (automated/robo-refund)' },
      }
    ]
  }
]; 